from graph.GraphFactory import BarabasiAlbertBuilder, DorogovtsevMendesBuilder, ErdosRenyiBuilder, GeographicBuilder, GilbertBuilder, GraphFactory, GridBuilder


factory = GraphFactory()

factory.set_builder(GridBuilder())
g = factory.build_graph(columns=5, rows=6, directed=True)
g.to_graphviz("../examples/grid30")
factory.set_builder(GridBuilder())
g = factory.build_graph(columns=10, rows=10, directed=True)
g.to_graphviz("../examples/grid100")
factory.set_builder(GridBuilder())
g = factory.build_graph(columns=50, rows=10, directed=True)
g.to_graphviz("../examples/grid500")

factory.set_builder(ErdosRenyiBuilder())
g = factory.build_graph(nodes=30, edges=15,)
g.to_graphviz("../examples/erdos30")
factory.set_builder(ErdosRenyiBuilder())
g = factory.build_graph(nodes=100, edges=40,)
g.to_graphviz("../examples/erdos100")
factory.set_builder(ErdosRenyiBuilder())
g = factory.build_graph(nodes=500, edges=300,)
g.to_graphviz("../examples/erdos500")


factory.set_builder(GilbertBuilder())
g = factory.build_graph(nodes=30, p=0.1, loops=True)
g.to_graphviz("../examples/gilbert30")
factory.set_builder(GilbertBuilder())
g = factory.build_graph(nodes=100, p=0.1, loops=True)
g.to_graphviz("../examples/gilbert100")
factory.set_builder(GilbertBuilder())
g = factory.build_graph(nodes=500, p=0.1, loops=True)
g.to_graphviz("../examples/gilbert500")

factory.set_builder(GeographicBuilder())
g = factory.build_graph(nodes=30, max_dist=0.1, loops=False)
g.to_graphviz("../examples/geo30")
factory.set_builder(GeographicBuilder())
g = factory.build_graph(nodes=100, max_dist=0.1, loops=False)
g.to_graphviz("../examples/geo100")
factory.set_builder(GeographicBuilder())
g = factory.build_graph(nodes=500, max_dist=0.1, loops=False)
g.to_graphviz("../examples/geo500")

factory.set_builder(BarabasiAlbertBuilder())
g = factory.build_graph(nodes=30, degree=10, loops=False)
g.to_graphviz("../examples/barabasi30")
factory.set_builder(BarabasiAlbertBuilder())
g = factory.build_graph(nodes=100, degree=40, loops=False)
g.to_graphviz("../examples/barabasi100")
factory.set_builder(BarabasiAlbertBuilder())
g = factory.build_graph(nodes=500, degree=200, loops=False)
g.to_graphviz("../examples/barabasi500")

factory.set_builder(DorogovtsevMendesBuilder())
g = factory.build_graph(nodes=30)
g.to_graphviz("../examples/dorogotsev30")
factory.set_builder(DorogovtsevMendesBuilder())
g = factory.build_graph(nodes=100)
g.to_graphviz("../examples/dorogotsev100")
factory.set_builder(DorogovtsevMendesBuilder())
g = factory.build_graph(nodes=500)
g.to_graphviz("../examples/dorogotsev500")

